### ISSUE TITLE
Candyman can perform his special on all angles

### ISSUE THREAD

**Issue by YinYin-Falcon** [metaphist/llb#4]

**Comment by metaphist** [comment]
Thanks, should be able to knock these out over the weekend.

**Comment by metaphist** [comment]
Enabled special for all angles. 

Not sure if that properly follows the rules? I thought Candyman special angles were specific angles, but in any case this airs on the side of NOT leaving an angle out that should be there. Will follow up later. Might just separate out his special as a specific section below him for clarity.

**Comment by YinYin-Falcon** [comment]
He actually can use it out of all swings and thus all angles - if you don't input any direction even the smash angle :)

**Comment by metaphist** [comment]
Cool. Can't push to the web from work at the moment, but I'll push later when I'm home. Code here is updated though.
