### ISSUE TITLE
Characters aren't loading

### ISSUE THREAD

**Issue by Codeman655** [metaphist/llb#7]
The characters don't appear to load. Not sure if it's a permissions issue on the webserver backend.

![nochars](https://user-images.githubusercontent.com/1981439/77235562-2693c280-6b8d-11ea-86eb-970835e58c31.gif)

**Comment by metaphist** [comment]
Ah, should have mentioned, there's probably a caching issue. Try clearing your cache, or try an incognito window.

**Comment by Codeman655** [comment]
We in there.
